ForControl/Controllers/AguaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ForControl.Controllers
{
    public class AguaController : Controller
    {
        // GET: Agua
        public ActionResult Index()
        {
            return View();
        }

        //public ActionResult costao()
        //{
        //    return new RedirectResult("http://costao.forcontrol.com.br");
        //}

    }
}

ForControl/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ForControl.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

ForControl/Views/Agua/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand topnav" href="@Url.Action("Index","Home")">For Control</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        @*<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#about">Sobre Nós</a>
                </li>
                <li>
                    <a href="#services">Serviços Prestados</a>
                </li>
                <li>
                    <a href="#contact">Contato</a>
                </li>
            </ul>
        </div>*@
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
<!-- Header -->
<a name="about"></a>
<div class="intro-header-mini">
</div>
<!-- /.intro-header -->
<!-- Page Content -->
<div class="content-section-b">

    <div class="container">

        <h4>Associações/Prefeituras com o serviço disponível</h4>
        <div class="row">
            <div class="col-sm-3">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <img class="img-responsive center-block" src="~/img/noimage.png" alt="">
                <h6>ASSOCIAÇÃO DE ÁGUA DE LINHA GERALDO</h6>
                <a href="http://agua.forcontrol.com.br"><span>Acessar</span> <i class="fa fa-external-link fa-fw"></i></a>
            </div>
            <div class="col-sm-3">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <img class="img-responsive center-block" src="~/img/noimage.png" alt="">
                <h6>ASSOCIAÇÃO DE ÁGUA ROTA DO SOL</h6>
                <a href="http://rotadosol.forcontrol.com.br"><span>Acessar</span> <i class="fa fa-external-link fa-fw"></i></a>
            </div>
            <div class="col-sm-3">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <img class="img-responsive center-block" src="~/img/noimage.png" alt="">
                <h6>ASSOCIAÇÃO DE ABASTECIMENTO DE AGUA LINHA LENZ</h6>
                <a href="http://lenz.forcontrol.com.br"><span>Acessar</span> <i class="fa fa-external-link fa-fw"></i></a>
            </div>
            <div class="col-sm-3">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <img class="img-responsive center-block" src="~/img/noimage.png" alt="">
                <h6>ASSOCIAÇÃO DE ABASTECIMENTO DE ÁGUA DE NOVA WESTFÁLIA</h6>
                <a href="http://novawestfalia.forcontrol.com.br"><span>Acessar</span> <i class="fa fa-external-link fa-fw"></i></a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <img class="img-responsive center-block" src="~/img/logo_apdl.png" alt="">
                <h6>APDL - ASSOCIAÇÃO PRÓ DESENVOLVIMENTO DE LANGUIRU</h6>
                <a href="http://www.apdl.com.br/FASWeb"><span>Acessar</span> <i class="fa fa-external-link fa-fw"></i></a>
            </div>
            <div class="col-sm-3">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <img class="img-responsive center-block" src="~/img/noimage.png" alt="">
                <h6>SOCIEDADE DE ABASTECIMENTO DE ÁGUA BEIJA-FLOR</h6>
                <a href="http://agua.forcontrol.com.br"><span>Acessar</span> <i class="fa fa-external-link fa-fw"></i></a>
            </div>
            <div class="col-sm-3">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <img class="img-responsive center-block" src="~/img/noimage.png" alt="">
                <h6>SOCIEDADE DE ABASTECIMENTO DE ÁGUA SÃO BENTO CENTRO</h6>
                <a href="http://saobento.forcontrol.com.br:8060/"><span>Acessar</span> <i class="fa fa-external-link fa-fw"></i></a>
            </div>
            <div class="col-sm-3">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <img class="img-responsive center-block" src="~/img/noimage.png" alt="">
                <h6>SOCIEDADE DE ÁGUA LINK WINK</h6>
                <a href="http://agua.forcontrol.com.br"><span>Acessar</span> <i class="fa fa-external-link fa-fw"></i></a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <img class="img-responsive center-block" src="~/img/logo_unicatu.jpg" alt="">
                <h6>UNICATÚ - ÁGUA E SOLO SOLUÇÕES EM SANEAMENTO LTDA</h6>
                <a href="http://unicatu.forcontrol.com.br"><span>Acessar</span> <i class="fa fa-external-link fa-fw"></i></a>
            </div>
        </div>
    </div>
        <!-- /.container -->

    </div>
<!-- /.content-section-b -->

ForControl/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand topnav" href="#">For Control</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#about">Sobre Nós</a>
                </li>
                <li>
                    <a href="#services">Serviços Prestados</a>
                </li>
                <li>
                    <a href="#contact">Contato</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>


<!-- Header -->
<a name="about"></a>
<div class="intro-header">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    @*<img align="middle" class="img-responsive" src="~/img/logo.png" alt="">*@
                    <h1>For Control</h1>
                    <h3>Assessoria Empresarial</h3>
                    <hr class="intro-divider">
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-skype fa-fw"></i> <span class="network-name">Skype</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-youtube fa-fw"></i> <span class="network-name">Youtube</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.intro-header -->
<!-- Page Content -->

<div class="content-section-a">

    <div class="container">

        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Portal do Consumidor de Água</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <p class="lead">
                    - Emissão de Segunda via<br />
                    - Visualização de Consumos<br />
                    - Emissão de Relatórios (Administradores)<br />
                    <br />
                    <a href="@Url.Action("Index","Agua")" class="btn btn-primary btn-lg"><i class="fa fa-external-link fa-fw"></i> <span class="network-name">Acessar</span></a>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <img class="img-responsive" src="~/img/logoFAS.png" alt="">
            </div>
        </div>

    </div>
    <!-- /.container -->

    <a name="services"></a>
    @*<div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Death to the Stock Photo:<br>Special Thanks</h2>
                    <p class="lead">A special thanks to <a target="_blank" href="http://join.deathtothestockphoto.com/">Death to the Stock Photo</a> for providing the photographs that you see in this template. Visit their website to become a member.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="~/img/ipad.png" alt="">
                </div>
            </div>

        </div>

    </div>*@
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Assessoria@*<br>by PSDCovers*@</h2>
                    @*<p class="lead">A For Control atende empresas de diversos tamanhos, tornando-os verdadeiros parceiros.</p>*@
                    <p class="lead">
                        - Terceirização de Atividades.<br />
                        - Análise de aspectos legais.<br />
                        - Estudo de viabilidade econômica.<br />
                        - Implantação de projetos terceirizáveis.<br />
                        - Acompanhamento e regularização das atividades.<br />
                        - Serviços de apoio a empresas terceirizadas.
                    </p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="~/img/um.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Consultoria</h2>
                    @*<p class="lead">A For Control atende empresas nos segmentos de transporte de cargas. O atendimento engloba Abertura, Assessoria Contábil e Fiscal.</p>*@
                    <p class="lead">
                        - Cooperativas de Transporte.<br />
                        - Cooperativas de Trabalhadores Autônomos.<br />
                        - Empresas de transporte rodoviário de cargas.<br />
                        - Saneamento básico: Integração de sistemas de controle com projetos de saneamento.
                    </p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="~/img/dois.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Soluções Pontuais</h2>
                    <p class="lead">
                        A For Control também atua em parceria com empresas de desenvolvimento de soluções na área de tecnologia de informação.<br />
                        - Iluminação Pública, Transparência Administrativa e serviços ao cidadão. <br />
                        Acesse <a target="_blank" href="http://www.fiscale.vc/">Fiscale.vc</a> e saiba mais sobre esta solução.
                    </p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <a target="_blank" href="http://www.fiscale.vc/"><img class="img-responsive" src="~/img/logofiscale21000.png" alt=""></a>
                </div>
            </div>
        </div>
        <!-- /.container -->
    </div>
    <!-- /.content-section-b -->

</div>
<!-- /.content-section-a -->

ForControl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-83517052-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-83517052-3');
    </script>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>For Control</title>
    <link rel="shortcut icon" type="image/png" href="~/img/logo.png" />
    @Styles.Render("~/Content/css")

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

    <form id="form1" runat="server">

        @RenderBody()

        <a name="contact"></a>
        <div class="banner">

            <div class="container">

                <div class="row">
                    <div class="col-lg-6">
                        <span>
                            <a href="mailto:contato@forcontrol.com.br?Subject=Contato%20informações"><i class="fa fa-envelope-o fa-lg"></i></a> contato@forcontrol.com.br<br />
                            (51) 3762-2414<br />
                            Avenida 1 Leste, 1020 - Sala 205<br />
                            Bairro Centro Administrativo - Teutônia<br />
                            Rio Grande do Sul - Brasil
                        </span>
                    </div>
                    @*<div class="col-lg-6">
                        <ul class="list-inline banner-social-buttons">
                            <li>
                                <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                            </li>
                            <li>
                                <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-youtube fa-fw"></i> <span class="network-name">Youtube</span></a>
                            </li>
                            <li>
                                <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                            </li>
                        </ul>
                    </div>*@
                </div>

            </div>
            <!-- /.container -->

        </div>
        <!-- /.banner -->
        <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-inline">
                            <li>
                                <a href="@Url.Action("Index","Home")">Home</a>
                            </li>
                            @*<li class="footer-menu-divider">&sdot;</li>
                            <li>
                                <a href="#about">Sobre Nós</a>
                            </li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li>
                                <a href="#services">Serviços Prestados</a>
                            </li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li>
                                <a href="#contact">Contato</a>
                            </li>*@
                        </ul>
                        <p class="copyright text-muted small">Copyright &copy; For Control 2016. Todos os direitos reservados</p>
                    </div>
                </div>
            </div>
        </footer>

    </form>

        

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>